version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: market24
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4868
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=market24
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=4868
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
